In [3]:
#!pip install torch

In [30]:
import torch
import numpy as np

In [9]:
x = torch.empty(3,3) # 2d with 3 element
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [11]:
x = torch.rand(2,2)  # random value
x

tensor([[0.4825, 0.3175],
        [0.5911, 0.2967]])

In [12]:
x = torch.zeros(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

In [15]:
x = torch.ones(3,2,dtype=int)
x

tensor([[1, 1],
        [1, 1],
        [1, 1]])

In [16]:
x.dtype

torch.int64

In [18]:
x.size()  # 3 rows 2 cols

torch.Size([3, 2])

In [19]:
# create from data i.e list 
z = torch.tensor([2.3,5,6,8,9])
z

tensor([2.3000, 5.0000, 6.0000, 8.0000, 9.0000])

In [20]:
a = torch.rand(2,2)
b = torch.rand(2,2)


In [21]:
a

tensor([[0.1012, 0.2182],
        [0.5537, 0.9854]])

In [22]:
b

tensor([[0.5672, 0.1116],
        [0.6843, 0.2375]])

In [29]:
c = a + b # element wise addition
c

tensor([[0.7696, 0.5480],
        [1.7917, 2.2083]])

In [28]:
c = torch.add(a,b)
c

tensor([[0.7696, 0.5480],
        [1.7917, 2.2083]])

In [27]:
# inline addition
# in pytorch every fucntion with underscore will do inplace addition.
b.add_(a)
b

tensor([[0.6684, 0.3298],
        [1.2380, 1.2229]])

In [32]:
r = torch.ones(3,3)
r

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
s = r.numpy()  # converting to numpy
s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [34]:
torch.cuda.is_available()

False

## AUTOGRAD

In [45]:
x = torch.randn(3, requires_grad=True)
x

tensor([ 0.2627, -0.9207, -1.1801], requires_grad=True)

In [46]:
y = x + 2
y

tensor([2.2627, 1.0793, 0.8199], grad_fn=<AddBackward0>)

In [47]:
z = y*y*2
z

tensor([10.2394,  2.3296,  1.3444], grad_fn=<MulBackward0>)

In [48]:
z = z.mean()
z

tensor(4.6378, grad_fn=<MeanBackward0>)

In [50]:
z.backward()
print(x.grad)

tensor([3.0169, 1.4390, 1.0932])


In [54]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_op = (weights * 3).sum()
    model_op.backward()
    print(weights.grad)

    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


## LINEAR REGRESSION

# numpy

In [55]:
import numpy as np

In [56]:
x = np.array([1,2,3,4], dtype=np.float32)
y = np.array([2,4,6,8], dtype=np.float32)

# 2*x

In [57]:
w = 0.0

In [58]:
def forward(x):
    return w * x


def loss(y, y_pred):
    return ((y_pred - y)**2).mean() 

def gradient(x,y,y_pred):
    return np.dot(2*x, y_pred-y).mean()

In [63]:
print(f"Prediction before training f(5) : {forward(5):.3f}")

lr = 0.01
epochs = 10

for e in range(epochs):
    # forward pass
    y_pred = forward(x)
    # loss calculation
    l = loss(y, y_pred)
    # gradient descent
    dw = gradient(x,y,y_pred)
    # update weights
    w-= lr * dw 

    if e % 1 == 0:
        print(f" epoch --> {e + 1} : w = {w :.3f}, loss = {l:.8f}")

print(f"Prediction after training f(5) : {forward(5):.3f}")

Prediction before training f(5) : 8.926
 epoch --> 1 : w = 1.914, loss = 0.34587651
 epoch --> 2 : w = 1.966, loss = 0.05534024
 epoch --> 3 : w = 1.986, loss = 0.00885440
 epoch --> 4 : w = 1.995, loss = 0.00141673
 epoch --> 5 : w = 1.998, loss = 0.00022668
 epoch --> 6 : w = 1.999, loss = 0.00003626
 epoch --> 7 : w = 2.000, loss = 0.00000580
 epoch --> 8 : w = 2.000, loss = 0.00000093
 epoch --> 9 : w = 2.000, loss = 0.00000015
 epoch --> 10 : w = 2.000, loss = 0.00000002
Prediction after training f(5) : 10.000


# pytorch

In [64]:
import torch

In [65]:
x = torch.tensor([1,2,3,4], dtype=torch.float32)
y = torch.tensor([2,4,6,8], dtype=torch.float32)


In [67]:
w = torch.tensor(0.0, dtype=torch.float32, requires_grad= True)

In [68]:
def forward(x):
    return w * x


def loss(y, y_pred):
    return ((y_pred - y)**2).mean() 

In [75]:
print(f"Prediction before training f(5) : {forward(5):.3f}")

lr = 0.01
epochs = 10

for e in range(epochs):
    # forward pass
    y_pred = forward(x)
    # loss calculation
    l = loss(y, y_pred)

    # for gradient 
    l.backward()

    with torch.no_grad():
        w-= lr * w.grad

    # zero gradients.
    w.grad.zero_()

    if e % 1 == 0:
        print(f" epoch --> {e + 1} : w = {w :.3f}, loss = {l:.8f}")

print(f"Prediction after training f(5) : {forward(5):.3f}")

Prediction before training f(5) : 9.999
 epoch --> 1 : w = 2.000, loss = 0.00000010
 epoch --> 2 : w = 2.000, loss = 0.00000007
 epoch --> 3 : w = 2.000, loss = 0.00000005
 epoch --> 4 : w = 2.000, loss = 0.00000004
 epoch --> 5 : w = 2.000, loss = 0.00000003
 epoch --> 6 : w = 2.000, loss = 0.00000002
 epoch --> 7 : w = 2.000, loss = 0.00000001
 epoch --> 8 : w = 2.000, loss = 0.00000001
 epoch --> 9 : w = 2.000, loss = 0.00000001
 epoch --> 10 : w = 2.000, loss = 0.00000001
Prediction after training f(5) : 10.000


### MODEL DESIGN

1. Design model (input_size, output_size, forward_pass)
2. Construct loss and optimiser
3. Training loop
   3.a) forward_pass : compute predictions
   3.b) backward_pass : gradients
   3.c) update_weight

In [79]:
import torch.nn as nn

In [91]:
x = torch.tensor([[1],[2],[3],[4]], dtype=torch.float32)
y = torch.tensor([[2],[4],[6],[8]], dtype=torch.float32)
x_test = torch.tensor([5], dtype = torch.float32)

In [90]:
n_samples, n_feature = x.shape

In [93]:
model = nn.Linear(n_feature,n_feature)

In [94]:
loss = nn.MSELoss()

In [95]:
lr = 0.01
epochs = 10
optimiser = torch.optim.SGD(model.parameters(), lr=lr)

In [97]:
print(f"Prediction before training f(5) : {model(x_test).item():.3f}")

lr = 0.01
epochs = 100

for e in range(epochs):
    # forward pass
    y_pred  = model(x)
    # loss calculation
    l = loss(y, y_pred)

    # for gradient 
    l.backward()

    optimiser.step()
    optimiser.zero_grad()

    if e % 10 == 0:
        [w,b] = model.parameters()
        print(f" epoch --> {e + 1} : w = {w[0][0].item() :.3f}, loss = {l:.8f}")

print(f"Prediction after training f(5) : {model(x_test).item():.3f}")

Prediction before training f(5) : 9.657
 epoch --> 1 : w = 1.834, loss = 0.04012112
 epoch --> 11 : w = 1.839, loss = 0.03778582
 epoch --> 21 : w = 1.843, loss = 0.03558649
 epoch --> 31 : w = 1.848, loss = 0.03351517
 epoch --> 41 : w = 1.853, loss = 0.03156442
 epoch --> 51 : w = 1.857, loss = 0.02972719
 epoch --> 61 : w = 1.861, loss = 0.02799693
 epoch --> 71 : w = 1.865, loss = 0.02636734
 epoch --> 81 : w = 1.869, loss = 0.02483263
 epoch --> 91 : w = 1.873, loss = 0.02338723
Prediction after training f(5) : 9.746
