In [1]:
#!pip install numpy
#!pip install matplotlib
#!pip install pandas
#!pip install -U scikit-learn

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Dataset/50_Startups.csv')
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
X = dataset.iloc[:,:-1].values
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:
y = dataset.iloc[:,4].values
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

X_label = LabelEncoder()
X[:,3] = X_label.fit_transform(X[:,3])
onehotencoder = ColumnTransformer(transformers=[('State',OneHotEncoder(),[3])],remainder='passthrough') #write the column
X = onehotencoder.fit_transform(X)
X


array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.2, random_state=0)

In [8]:
from sklearn.linear_model import LinearRegression
regression = LinearRegression()
regression.fit(X_train,Y_train)

LinearRegression()

In [9]:
y_pred = regression.predict(X_test)

In [10]:
y_pred

array([103015.20159795, 132582.27760816, 132447.73845175,  71976.09851258,
       178537.48221057, 116161.24230167,  67851.69209676,  98791.73374687,
       113969.43533014, 167921.06569552])

In [11]:
Y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

In [12]:
#!pip install statsmodels 

In [13]:
import statsmodels.api as sm
X = np.append(arr = np.ones((50,1)).astype(int),values=X,axis=1)

In [14]:
X

array([[1, 0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1, 1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [1, 0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1, 1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1, 1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1, 1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1, 1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1, 1.0, 0.0, 0.0, 78013.11, 121597.55, 264

In [15]:
X_opt = X[:,[0,1,2,4,5,6]]
X_opt


array([[1, 0.0, 0.0, 165349.2, 136897.8, 471784.1],
       [1, 1.0, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 0.0, 1.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 0.0, 144372.41, 118671.85, 383199.62],
       [1, 0.0, 1.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 0.0, 131876.9, 99814.71, 362861.36],
       [1, 1.0, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 0.0, 1.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 0.0, 120542.52, 148718.95, 311613.29],
       [1, 1.0, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 0.0, 1.0, 101913.08, 110594.11, 229160.95],
       [1, 1.0, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 0.0, 1.0, 93863.75, 127320.38, 249839.44],
       [1, 1.0, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 0.0, 1.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 0.0, 114523.61, 122616.84, 261776.23],
       [1, 1.0, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 0.0, 94657.16, 145077.58, 282574.31],
       [1, 0.0, 1.0, 9

In [16]:
X_opt = np.array(X_opt, dtype=float)
regression_ols = sm.OLS(endog=y,exog=X_opt).fit()
print(regression_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     169.9
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           1.34e-27
Time:                        15:23:33   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1063.
Df Residuals:                      44   BIC:                             1074.
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.008e+04   6952.587      7.204      0.0

In [17]:
X_opt = X[:,[0,2,4,5,6]]
X_opt

array([[1, 0.0, 165349.2, 136897.8, 471784.1],
       [1, 0.0, 162597.7, 151377.59, 443898.53],
       [1, 1.0, 153441.51, 101145.55, 407934.54],
       [1, 0.0, 144372.41, 118671.85, 383199.62],
       [1, 1.0, 142107.34, 91391.77, 366168.42],
       [1, 0.0, 131876.9, 99814.71, 362861.36],
       [1, 0.0, 134615.46, 147198.87, 127716.82],
       [1, 1.0, 130298.13, 145530.06, 323876.68],
       [1, 0.0, 120542.52, 148718.95, 311613.29],
       [1, 0.0, 123334.88, 108679.17, 304981.62],
       [1, 1.0, 101913.08, 110594.11, 229160.95],
       [1, 0.0, 100671.96, 91790.61, 249744.55],
       [1, 1.0, 93863.75, 127320.38, 249839.44],
       [1, 0.0, 91992.39, 135495.07, 252664.93],
       [1, 1.0, 119943.24, 156547.42, 256512.92],
       [1, 0.0, 114523.61, 122616.84, 261776.23],
       [1, 0.0, 78013.11, 121597.55, 264346.06],
       [1, 0.0, 94657.16, 145077.58, 282574.31],
       [1, 1.0, 91749.16, 114175.79, 294919.57],
       [1, 0.0, 86419.7, 153514.11, 0.0],
       [1, 0.0, 76253

In [18]:
X_opt = np.array(X_opt, dtype=float)
regression_ols = sm.OLS(endog=y,exog=X_opt).fit()
print(regression_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.946
Method:                 Least Squares   F-statistic:                     217.2
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           8.49e-29
Time:                        15:32:09   Log-Likelihood:                -525.38
No. Observations:                  50   AIC:                             1061.
Df Residuals:                      45   BIC:                             1070.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.011e+04   6647.870      7.537      0.0

In [20]:
X_opt = X[:,[0,4,5,6]]
X_opt

array([[1, 165349.2, 136897.8, 471784.1],
       [1, 162597.7, 151377.59, 443898.53],
       [1, 153441.51, 101145.55, 407934.54],
       [1, 144372.41, 118671.85, 383199.62],
       [1, 142107.34, 91391.77, 366168.42],
       [1, 131876.9, 99814.71, 362861.36],
       [1, 134615.46, 147198.87, 127716.82],
       [1, 130298.13, 145530.06, 323876.68],
       [1, 120542.52, 148718.95, 311613.29],
       [1, 123334.88, 108679.17, 304981.62],
       [1, 101913.08, 110594.11, 229160.95],
       [1, 100671.96, 91790.61, 249744.55],
       [1, 93863.75, 127320.38, 249839.44],
       [1, 91992.39, 135495.07, 252664.93],
       [1, 119943.24, 156547.42, 256512.92],
       [1, 114523.61, 122616.84, 261776.23],
       [1, 78013.11, 121597.55, 264346.06],
       [1, 94657.16, 145077.58, 282574.31],
       [1, 91749.16, 114175.79, 294919.57],
       [1, 86419.7, 153514.11, 0.0],
       [1, 76253.86, 113867.3, 298664.47],
       [1, 78389.47, 153773.43, 299737.29],
       [1, 73994.56, 122782.75, 30

In [21]:
X_opt = np.array(X_opt, dtype=float)
regression_ols = sm.OLS(endog=y,exog=X_opt).fit()
print(regression_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.951
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     296.0
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           4.53e-30
Time:                        15:40:06   Log-Likelihood:                -525.39
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      46   BIC:                             1066.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       5.012e+04   6572.353      7.626      0.0

In [22]:
X_opt = X[:,[0,4,6]]
X_opt

array([[1, 165349.2, 471784.1],
       [1, 162597.7, 443898.53],
       [1, 153441.51, 407934.54],
       [1, 144372.41, 383199.62],
       [1, 142107.34, 366168.42],
       [1, 131876.9, 362861.36],
       [1, 134615.46, 127716.82],
       [1, 130298.13, 323876.68],
       [1, 120542.52, 311613.29],
       [1, 123334.88, 304981.62],
       [1, 101913.08, 229160.95],
       [1, 100671.96, 249744.55],
       [1, 93863.75, 249839.44],
       [1, 91992.39, 252664.93],
       [1, 119943.24, 256512.92],
       [1, 114523.61, 261776.23],
       [1, 78013.11, 264346.06],
       [1, 94657.16, 282574.31],
       [1, 91749.16, 294919.57],
       [1, 86419.7, 0.0],
       [1, 76253.86, 298664.47],
       [1, 78389.47, 299737.29],
       [1, 73994.56, 303319.26],
       [1, 67532.53, 304768.73],
       [1, 77044.01, 140574.81],
       [1, 64664.71, 137962.62],
       [1, 75328.87, 134050.07],
       [1, 72107.6, 353183.81],
       [1, 66051.52, 118148.2],
       [1, 65605.48, 107138.38],
       [1

In [23]:
X_opt = np.array(X_opt, dtype=float)
regression_ols = sm.OLS(endog=y,exog=X_opt).fit()
print(regression_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.950
Model:                            OLS   Adj. R-squared:                  0.948
Method:                 Least Squares   F-statistic:                     450.8
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           2.16e-31
Time:                        18:04:27   Log-Likelihood:                -525.54
No. Observations:                  50   AIC:                             1057.
Df Residuals:                      47   BIC:                             1063.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.698e+04   2689.933     17.464      0.0

In [26]:
X_opt = X[:,[0,4]]
X_opt

array([[1, 165349.2],
       [1, 162597.7],
       [1, 153441.51],
       [1, 144372.41],
       [1, 142107.34],
       [1, 131876.9],
       [1, 134615.46],
       [1, 130298.13],
       [1, 120542.52],
       [1, 123334.88],
       [1, 101913.08],
       [1, 100671.96],
       [1, 93863.75],
       [1, 91992.39],
       [1, 119943.24],
       [1, 114523.61],
       [1, 78013.11],
       [1, 94657.16],
       [1, 91749.16],
       [1, 86419.7],
       [1, 76253.86],
       [1, 78389.47],
       [1, 73994.56],
       [1, 67532.53],
       [1, 77044.01],
       [1, 64664.71],
       [1, 75328.87],
       [1, 72107.6],
       [1, 66051.52],
       [1, 65605.48],
       [1, 61994.48],
       [1, 61136.38],
       [1, 63408.86],
       [1, 55493.95],
       [1, 46426.07],
       [1, 46014.02],
       [1, 28663.76],
       [1, 44069.95],
       [1, 20229.59],
       [1, 38558.51],
       [1, 28754.33],
       [1, 27892.92],
       [1, 23640.93],
       [1, 15505.73],
       [1, 22177.74],
 

In [27]:
X_opt = np.array(X_opt, dtype=float)
regression_ols = sm.OLS(endog=y,exog=X_opt).fit()
print(regression_ols.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.947
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     849.8
Date:                Mon, 30 Jan 2023   Prob (F-statistic):           3.50e-32
Time:                        18:09:48   Log-Likelihood:                -527.44
No. Observations:                  50   AIC:                             1059.
Df Residuals:                      48   BIC:                             1063.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       4.903e+04   2537.897     19.320      0.0