In [1]:
# pip install tensorflow
# pip install keras
#!pip install thanos

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv('Dataset/Churn_Modelling.csv')
x = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [6]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [7]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer

label_encoder_x_1 = LabelEncoder()
x[:,1] = label_encoder_x_1.fit_transform(x[:,1])


In [8]:
label_encoder_x_2 = LabelEncoder()
x[:,2] = label_encoder_x_2.fit_transform(x[:,2])


In [9]:
onehotencoder = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder = 'passthrough')
x = np.array(onehotencoder.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [11]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
x_train = sc_X.fit_transform(x_train)
x_test = sc_X.transform(x_test)

In [12]:
import keras
TF_CPP_MIN_LOG_LEVEL="2"

2023-02-16 11:42:27.060112: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-16 11:42:27.374639: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2023-02-16 11:42:27.374664: I tensorflow/compiler/xla/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2023-02-16 11:42:28.517340: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
classifier = Sequential()

2023-02-16 11:42:29.577886: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2023-02-16 11:42:29.579357: W tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: UNKNOWN ERROR (303)
2023-02-16 11:42:29.579415: I tensorflow/compiler/xla/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (sahil-ThinkPad-X270-W10DG): /proc/driver/nvidia/version does not exist
2023-02-16 11:42:29.579845: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
classifier.add(Dense(activation='relu',units=50))

In [16]:
classifier.add(Dense(activation='relu',units=50))

In [17]:
classifier.add(Dense(activation='sigmoid',units=1))

In [18]:
x_train.shape

(7000, 12)

In [19]:
y_train.shape

(7000,)

In [20]:
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics=['accuracy'])
classifier.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
219/219 [==============================] - 2s 3ms/step - loss: 0.4651 - accuracy: 0.7953
Epoch 2/100
219/219 [==============================] - 1s 3ms/step - loss: 0.4029 - accuracy: 0.8291
Epoch 3/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3686 - accuracy: 0.8493
Epoch 4/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3494 - accuracy: 0.8561
Epoch 5/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3446 - accuracy: 0.8563
Epoch 6/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3386 - accuracy: 0.8599
Epoch 7/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3359 - accuracy: 0.8609
Epoch 8/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3315 - accuracy: 0.8641
Epoch 9/100
219/219 [==============================] - 1s 2ms/step - loss: 0.3302 - accuracy: 0.8661
Epoch 10/100
219/219 [==============================] - 1s 3ms/step - loss: 0.3290 - accura

In [21]:
y_pred = classifier.predict(x_test)

94/94 [==============================] - 0s 2ms/step


In [25]:
y_pred = (y_pred > 0.5)

In [27]:
# classifier.build()
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[2225  154]
 [ 291  330]]


0.8516666666666667

In [ ]:
# classifier.summary()